export const projects = [
  {
    title: 'truco-henry-app',
    description: "This is the final project built in the last stage of the bootcamp. It was developed by a team of 6 people using the SCRUM and agile methodologies and GitHub to manage the project’s versions. It consists in a very popular Card Game played in some parts of Latin America.Users can create an account and make friends as well as engage in a small community. It was built using Socket.io, Postgres, Sequelize, React, Express are the most important libraries. The project reached one of the highest scores of the bootcamp.",
    image: '/images/truco-henry-app.png',
    tags: ['Sequelize', 'Postgres', "React", "Express", "Socket.io"],
    source: 'https://github.com/nelsonosorio3/truco-online',
    visit: 'https://trucohenry.com/',
    id: 0,
  },

  {
    title: 'videogames-app',
    description: "The project consists of calling an API (https://rawg.io/apidocs) to show an initial set of 80 videogames on the /home page to see a variety of items and click over one and to access the details about the platforms, genres, name, released date, etc.The app has a database built with Sequelize and Postgres where the client can add new games by filling up a form. For the front-end was developed using React and Redux. ",
    image: '/images/videogame-app.png',
    tags: ['Sequelize', 'Postgres', "React", "Express"],
    source: 'https://github.com/webDesignMumeishon/videogames-main',
    visit: 'https://videogames-app-pi.netlify.app/',
    id: 1,
  },

  {
    title: 'steam-deals-app',
    description: "The project was part of a challenge and consists of calling an API (https://www.cheapshark.com/api/1.0/deals?storeID=1&upperPrice=15) to show an initial set of games deals.It is a SPA built in react using plain CSS and some react icons and loaders. It has different functionalities, among them, a search bar to look for deals by the game's name. Also, deals can be added to the car, and when clicking on the car icon a panel with all the deals and the total price will be displayed.",
    image: '/images/steam-deals-app.png',
    tags: ["React", "HTML", "CSS"],
    source: 'https://github.com/webDesignMumeishon/steam-deals-app',
    visit: 'https://steam-deals-app.netlify.app/',
    id: 2,
  },

  {
    title: 'find-henry-app',
    description: "The app consists of a map where all the registered and verified users can be seen in the location that was selected by them. The app was meant to have all the henry bootcamp’s graduates connected across the world. The back-end was developed using MongoDB & Mongoose for the database, and Express. React.js for client side. Also, the site has its own admin page. A login system was implemented together with a reset password.",
    image: '/images/find-henry-app.png',
    tags: ['MongoDB', 'Mongoose', "React", "Express"],
    source: 'https://github.com/webDesignMumeishon/red-henry',
    visit: 'https://find-closest-henry.netlify.app/',
    id: 3,
  },
  {
    title: 'Movie App',
    description: "The project consists of calling an API (http://www.omdbapi.com/). The user types the movie in the search bar, after clicking the API is called and a set of movies in the main page are shown with details displayed, to see further details the user have to click over the name. Every single movie can be added to the favorite sections.",
      image: '/images/movie-app.png',
      tags: ['React', 'Redux', "AJAX"],
    source: 'https://github.com/webDesignMumeishon/movie-app',
    visit: 'https://movie-app-mumeishon.netlify.app/',
    id: 4,
  },
  {
    title: 'books-counter-app',
    description: "This app was built behind the idea of the data structure STACK. A stack is an abstract data type that holds an ordered, linear sequence of items. In contrast to a queue, a stack is a last in, first out (LIFO) structure. It was developed only using plain vanilla JavaScript, HTML and CSS.",
    image: '/images/book-stack.png',
    tags: ['Javascript', 'HTML', 'CSS'],
    source: 'https://github.com/webDesignMumeishon/books-counter-app',
    visit: 'https://webdesignmumeishon.github.io/books-counter-app/',
    id: 5,
  },
  {
    title: 'weather-app',
    description: "The app was developed during the bootcamp course. It was the first project built after learning React.The app consists in calling an external API that provides information about the current weather of any city in the world. The cities get accumulated in several cards in the cards section.The technologies used are React.js, JavaScript, HTML and CS",
    image: '/images/weather-app.png',
    tags: ['Javascript', 'HTML', 'CSS', 'React'],
    source: 'https://github.com/webDesignMumeishon/weather-app',
    visit: 'https://weather-app-tomasmacchi.netlify.app/',
    id: 6,
  },
  {
    title: 'todo-app',
    description: "The app is a simple todo application with a database set up in Firebase. It was built meanwhile looking for my first developer job, to sharp my React/Redux skills",
    image: '/images/todo-app.png',
    tags: ['Javascript', 'Redux', 'CSS', 'React', 'Firebase'],
    source: 'https://github.com/webDesignMumeishon/evernote-clone',
    visit: 'https://evernote-clone-d7098.web.app/',
    id: 7,
  },
  {
    title: 'student-profiles-app',
    description: "This app was created as part of a challenge sent by Hatchwats platform to assess my front-end skills. It consist in calling an API which has an array of students.The technologies used were React, Javascript, HTML and CSS.",
    image: '/images/student-profiles-app.png',
    tags: ['Javascript', 'CSS', 'React', 'HTML'],
    source: 'https://github.com/webDesignMumeishon/challenge-student-profiles',
    visit: 'https://challenge-students-profiles.netlify.app/',
    id: 8,
  },
  {
    title: 'meme-generator-app',
    description: "This is my first app created after learning TypeScript. It calls an API which brings a set of popular memes. You can add a title in the bottom ass well as the top, making the image an authentic meme creation.",
    image: '/images/meme-generator-app.png',
    tags: ['TypeScript', 'CSS', 'React', 'HTML'],
    source: 'https://github.com/webDesignMumeishon/meme-generator-app',
    visit: 'https://meme-generator-typescript-app.netlify.app/',
    id: 9,
  },
  {
    title: 'ping-pong-app',
    description: "This app was created as part of a challenge given by a Gaming Company. It is the classic game Ping Pong. It is played by two person simultaneously.",
    image: '/images/ping-pong-app.png',
    tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/webDesignMumeishon/ping-pong-app',
    visit: 'https://ping-pong-app-challenge.netlify.app/',
    id: 10,
  },
  {
    title: 'los-angeles-mountain',
    description: "This is a landing page design and created for my first client ever. It was developed using Vainilla JavaScript, Html and Css. It is a fully responsive site adaptable to any device.",
    image: '/images/los-angeles-mountain.png',
    tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/webDesignMumeishon/landing-page-mountains',
    visit: 'https://landing-page-mountains.netlify.app/',
    id: 11,
  },
  {
    title: 'speed-typing-game',
    description: "Speed Typing Game is a game in which a person can test the speed in his writing. The app was developed while improving my typescript skills.",
    image: '/images/speed-typing-game.png',
    tags: ['JavaScript', 'CSS', 'HTML', "React", "TypeScript"],
    source: 'https://github.com/webDesignMumeishon/speed-typing-game',
    visit: 'https://speed-typing-game-app.netlify.app/',
    id: 12,
  },
  {
    title: 'task-tracker-app',
    description: "This was my first React Single Page Application. It was built by following a tutorial. It is fully responsive",
    image: '/images/task-tracker.png',
    tags: ['JavaScript', 'CSS', 'HTML', "React"],
    source: 'https://github.com/webDesignMumeishon/react-task-tracker',
    visit: 'https://app-task-tracker.netlify.app/',
    id: 13,
  },
  {
    title: 'scrimba-capstone-project',
    description: "This is a project built as part of the Scrimba React Bootcamp following a step-by-step tutorial to apply all the knowledge learned in the course. The project was originally constructed using only Javascript, but on this occasion, I have included TypeScript.",
    image: '/images/capstone-project-scrimba.png',
    tags: ['JavaScript', 'TypeScript', "React"],
    source: 'https://github.com/webDesignMumeishon/capstone-project-scrimba',
    visit: 'https://scrimba-capstone-project-macchi.netlify.app/',
    id: 14,
  },
];

export const TimeLineData = [
  { year: "03/01/2020", text: 'Started my journey into IT', },
  { year: "06/01/2021", text: 'Enrolled in Henry Bootcamp', },
  { year: "12/04/2021", text: 'Got my first React Developer Job at Devlights-Argentina.', },
];